<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{082901b3-abcc-478c-8f65-6930cc000521}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Action Name="motor" Id="{cdd9b3f3-26f6-4587-9151-2f12ff38b31e}">
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Action>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="MAIN.motor">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>